// Datos de las imágenes con títulos, descripciones y características
const images = [
	new Fotos("./img/despegando (2).png", "Despegando de Barcelona", "Inicio del viaje hacia Londres", ["Primer día", "Barcelona-Londres", "Duración del vuelo: 2h 30m", "Londres: Capital de Reino Unido"]),
	new Fotos("./img/londres (2).png", "Vista de Londres desde una mochila", "Una perspectiva única de la ciudad", ["Minomi aventurero", "Viajero", "Curioso", "Explorador urbano"]),
	new Fotos("./img/catedral.png", "Catedral de Westminster", "Uno de los monumentos más icónicos de Londres", ["Construida entre 1895 y 1903", "Sede principal de la Iglesia católica en Inglaterra", "Arquitectura neobizantina", "Importante lugar religioso y turístico de Londres"]),
	new Fotos("./img/bigben.png", "El Big Ben de Londres", "La famosa torre del reloj", ["Inaugurado en 1859", "Torre más famosa de Londres", "Símbolo histórico del Reino Unido", "Ubicado junto al Parlamento británico"]),
	new Fotos("./img/phone.png", "Cabina de teléfono londinense", "Las tradicionales cabinas rojas de Londres", ["Minomi en Londres", "Cabina roja icónica", "Turismo británico", "Foto típica londinense"]),
	new Fotos("./img/halminton.png", "Musical Hamilton - Acto I", "Experiencia teatral en el West End", ["Minomi y Yolanda en el West End", "Musical Hamilton", "Noche de teatro en Londres", "Experiencia inolvidable"]),
	new Fotos("./img/hamilton2.png", "Musical Hamilton - Acto II", "Una noche de teatro memorable", ["Victoria Palace Theatre", "Creado por Lin-Manuel Miranda", "Estrenado en Londres en 2017", "Musical sobre la vida de Alexander Hamilton", "Éxito mundial ganador de premios Tony y Olivier"]),
	new Fotos("./img/witches.png", "Musical Wicked", "La historia de las brujas del Mago de Oz", ["Apollo Victoria Theatre", "Musical creado por Stephen Schwartz", "Estrenado en Londres en 2006", "Historia no contada de las brujas de Oz", "Uno de los musicales más exitosos del mundo"]),
	new Fotos("./img/nottinghillb.png", "Librería Notting Hill", "La famosa librería de la película Notting Hill", ["The Notting Hill Bookshop", "Inspiró la película Notting Hill", "Barrio londinense de Notting Hill", "Lugar turístico muy visitado", "Escenario icónico del cine romántico"]),
	new Fotos("./img/nottinghllinside.png", "Interior de Notting Hill", "Dentro de la icónica librería", ["Interior acogedor y cinematográfico", "Librería especializada en viajes", "Ambiente clásico londinense", "Zona famosa por la película Notting Hill", "Experiencia cultural en Londres"]),
	new Fotos("./img/nottinghillhouse.png", "Casa de la película Notting Hill", "Ubicación de rodaje principal", ["Casa azul de la película Notting Hill", "Rodaje protagonizado por Julia Roberts", "Película estrenada en 1999", "Uno de los lugares más fotografiados", "Símbolo del cine romántico británico"]),
	new Fotos("./img/portobello.png", "Paseando por Portobello", "Famoso mercado de antigüedades", ["Portobello Road Market", "Mercado histórico de Londres", "Famoso por antigüedades y arte", "Ubicado en el barrio de Notting Hill", "Uno de los mercados más populares de Europa"]),
	new Fotos("./img/relax.png", "Tomando té en el bar de Teatro Soho", "Un momento de relajación", ["Barrio Soho de Londres", "Tradición británica del té", "Zona famosa por teatros y musicales", "Ambiente relajado y cultural", "Descanso después del recorrido turístico"]),
	new Fotos("./img/puentelondres.png", "Mirando al puente de Londres", "Vistas del icónico Puente de la Torre", ["Tower Bridge de Londres", "Inaugurado en 1894", "Uno de los puentes más famosos del mundo", "Símbolo arquitectónico británico", "Vistas panorámicas del río Támesis"]),
	new Fotos("./img/visita.png", "Visita especial", "Un momento especial durante el viaje", ["Encuentro inesperado", "Recuerdo inolvidable", "Nueva amistad", "Foto espontánea"]),
	new Fotos("./img/adios.png", "Despedida de Londres", "Última foto antes de regresar", ["Vista nocturna desde el avión", "Luces de Londres al anochecer", "Regreso después del viaje", "Últimos recuerdos de la ciudad", "Final de la aventura londinense"])
];
